name: restaurant_customer
description: "A new Flutter project."

publish_to: "none"

version: 3.2.6+36

environment:
  sdk: ">=3.2.3 <4.0.0"

flutter_gen:
  output: lib/generated/flutter_gen/

dependencies:
  responsive_builder: ^0.7.0
  auto_size_text: ^3.0.0
  file_picker: ^6.1.1
  marquee: ^2.2.3
  text_scroll: ^0.2.0
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1
  just_the_tooltip: ^0.0.12
  badges:

  #?################# Image handling
  flutter_image_compress: ^2.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  intl_phone_field: ^3.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  env_banner: ^1.0.0+2
  fancy_shimmer_image: ^2.0.3
  carousel_slider:
  dropdown_button2: ^2.3.9
  pinput: ^3.0.1

  #  firebase_analytics: ^10.10.0
  firebase_core: ^2.28.0
  firebase_messaging: ^14.8.0

  flutter_local_notifications: ^17.0.0
  #  flutter_foreground_task: ^6.1.3
  device_info_plus: ^10.1.2
  package_info_plus: ^6.0.0

  #  device_preview: ^1.1.0

  flutter_screenutil: ^5.9.0

  injectable: ^2.4.1
  # Flutter pub run build_runner build  --delete-conflicting-outputs
  get_it: ^7.7.0

  go_router: ^12.1.1

  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_gen: ^5.3.2
  intl: ^0.19.0
  app_settings: ^5.1.1
  either_dart: ^1.0.0
  dio: ^5.3.4
  flutter_form_builder: ^9.1.1
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  google_maps_flutter: ^2.6.0
  logger: ^2.2.0
  signalr_netcore: ^1.3.7
  web_socket_channel: ^2.4.5
  responsive_framework: ^1.4.0
  glassmorphism_widgets: ^0.2.2
  form_builder_validators: ^10.0.1
  fluttertoast: ^8.2.4
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  sliver_tools: ^0.2.12
  infinite_scroll_pagination: ^4.0.0
  bloc_concurrency: ^0.2.5
  dotted_border: ^2.1.0
  loading_overlay: ^0.3.0
  location: ^5.0.3
  fl_location: ^3.0.0
  permission_handler: ^11.3.1
  uuid: ^3.0.7
  geolocator: ^11.0.0
  advertising_id: ^2.6.0
  app_tracking_transparency: ^2.0.6
  background_location: ^0.13.0
  flutter_polyline_points: ^2.0.0
  workmanager: ^0.5.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  loader_overlay: ^4.0.0
  url_launcher: ^6.2.5
  mime: ^1.0.5
  http_parser: ^4.0.2
  modal_bottom_sheet: ^3.0.0
  image_cropper: ^5.0.1
  google_sign_in_ios: ^5.7.7
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  intl_phone_number_input: ^0.7.4
  geocoding: ^3.0.0
  googleapis_auth: ^1.3.0
  dotted_line: ^3.2.2
  equatable: ^2.0.5
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_flavorizr: ^2.2.2
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  injectable_generator: ^2.6.1

  flutter_lints: ^2.0.3

flutter:
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/fonts/gothic/

  fonts:
    - family: ITCHandelGothicArabic
      fonts:
        - asset: assets/fonts/gothic/ITCHandelGothicArabic-W23Hv.ttf
          weight: 800
        - asset: assets/fonts/gothic/ITCHandelGothicArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/gothic/ITCHandelGothicArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/gothic/ITCHandelGothicArabic-Light.ttf
          weight: 300

  uses-material-design: true
flutter_intl:
  enabled: true
